[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "moderators"
dynamic = ["version"]
description = "Moderators: One package to moderate them all"
readme = "README.md"
requires-python = ">=3.9"
authors = [{ name = "Moderators Team" }]
dependencies = [
  "huggingface-hub>=0.22",
  "requests"
]

[project.urls]
Homepage = "https://github.com/viddexa/moderators"
Source = "https://github.com/viddexa/moderators"
"Bug Reports" = "https://github.com/viddexa/moderators/discussions/categories/q-a"
Changelog = "https://github.com/viddexa/moderators/releases"

[project.optional-dependencies]
transformers = ["transformers>=4.36"]
dev = [
  "pytest>=7.0",
  "pillow>=9.0",
  "ruff"
]

[project.scripts]
moderators = "moderators.cli:main"

[tool.hatch.version]
path = "src/moderators/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/moderators"]